#public keys
madscientistpublic ='BbqE9HcuPMsDvNYFHB8KUNVr1sSmSzQev6JfGgJd8HDm'
vupublic = '6L3cCz3j6sPBCcJf29ubqDJFpLoVvQi3YuGZWLCremDF'
uclpublic = '4BK1UY1zz8zL8mPXqhBybcRex6YAKtVTiFegjsyNGAaD'
#private keys
madscientistpassword = 'BNkgbo4vVbKZCXkRw3hMjjhDRQB6mNp1wzizdWUjfuGz'
vupassword = 'ATZwuTxm82LFCkkkSfLhGnAipdREiCFoJ4Ac52r8Ut7C'
uclpassword = '3fJ9n3U3UC5QVpCbzaVgbHkLUi3rM9a2ePx8Zsb11wFP'