#public keys
madscientistpublic ='HHn47xkPXM6gxT5nVrTKnuiQFUocseBQpxmaiEjQHaKq'
vupublic = '4BTn5YzemyLh6qo4VVCxG5sraMFsUD7CAwj7rQMEZGhZ'
uclpublic = 'AWiS5TViGwupNBQGHEv1uXMHhg5nLYzyKvHM9dcsSTeU'
#private keys
madscientistpassword = 'GPBEM7C2PMDTpKR9TELHP9Ziy3bZ5KSgEHdwcJCNJ8s8'
vupassword = '5QxyhCDRfexELaoGp2Y9nw3DvTRWeJTeXmny5iYVJiek'
uclpassword = 'EkTYq5TCzJVppJCkGwweYN33oAQRw1yY56VB2NtoNkQ3'